/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrburnet;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author braya
 */
public class ROBOTOPERATIVO extends javax.swing.JFrame {

    /**
     * Creates new form ROBOTOPERATIVO
     */
    public ROBOTOPERATIVO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPuerto = new javax.swing.JTextField();
        jTextFieldmarca = new javax.swing.JTextField();
        jTextFieldDireccionMac = new javax.swing.JTextField();
        jTextFieldid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BtVolverRU = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrburnet/Recursos/HBWallpaperR.jpg"))); // NOI18N
        jLabel7.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("PUERTO");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 160, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REGISTRAR NUEVO ROBOT OPERATIVO");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ID ROBOT");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 160, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("MARCA");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 160, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("DIRECCION MAC");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 117, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("NOMBRE");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 160, -1));
        getContentPane().add(jTextFieldPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 117, -1));

        jTextFieldmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 117, -1));
        getContentPane().add(jTextFieldDireccionMac, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 117, -1));
        getContentPane().add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 117, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR DATOS DEL ROBOT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 320, 250));

        BtVolverRU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrburnet/IFMenu/BTVolverMP1.png"))); // NOI18N
        BtVolverRU.setBorderPainted(false);
        BtVolverRU.setContentAreaFilled(false);
        BtVolverRU.setFocusPainted(false);
        BtVolverRU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BtVolverRUTagBTVolver(evt);
            }
        });
        BtVolverRU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtVolverRUVolverMenuInicio(evt);
            }
        });
        BtVolverRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVolverRUActionPerformed(evt);
            }
        });
        getContentPane().add(BtVolverRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 60));

        jButtonConfirmar.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(255, 255, 0));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrburnet/IFMenu/check-mark2_1.png"))); // NOI18N
        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.setBorder(null);
        jButtonConfirmar.setBorderPainted(false);
        jButtonConfirmar.setContentAreaFilled(false);
        jButtonConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConfirmar.setRequestFocusEnabled(false);
        jButtonConfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmarMouseClicked(evt);
            }
        });
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 120, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrburnet/IFMopciones/AgregarRobot1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 100, 100));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mrburnet/Recursos/HBWallpaperR.jpg"))); // NOI18N
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmarcaActionPerformed

    private void BtVolverRUTagBTVolver(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BtVolverRUTagBTVolver
        // TODO add your handling code here:
        BtVolverRU.setToolTipText("Volver");
    }//GEN-LAST:event_BtVolverRUTagBTVolver

    private void BtVolverRUVolverMenuInicio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtVolverRUVolverMenuInicio
        // TODO add your handling code here:
        FormOpciones inicioSesio = new FormOpciones();
        inicioSesio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtVolverRUVolverMenuInicio

    private void jButtonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmarMouseClicked
        // TODO add your handling code here:
 
        Icon icono = new ImageIcon(getClass().getResource("Recursos//Mensaje6.png"));
        UIManager UI=new UIManager();
        UI.put("OptionPane.background", Color.BLACK);
        UI.put("Panel.background", Color.BLACK);
        UI.put("Button.background", Color.YELLOW);
        UI.put("OptionPane.messagebackground", Color.BLACK);
        UI.put("OptionPane.okButtonText","REGRESAR");
        JOptionPane.showMessageDialog(rootPane, null,null,JOptionPane.PLAIN_MESSAGE,icono);
        this.jTextFieldid.setText("");
        this.jTextFieldDireccionMac.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldPuerto.setText("");
        this.jTextFieldmarca.setText("");
        

    }//GEN-LAST:event_jButtonConfirmarMouseClicked

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void BtVolverRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVolverRUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVolverRUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROBOTOPERATIVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROBOTOPERATIVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROBOTOPERATIVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROBOTOPERATIVO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROBOTOPERATIVO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtVolverRU;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldDireccionMac;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPuerto;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldmarca;
    // End of variables declaration//GEN-END:variables
}
